# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: gateway-dev
    image: caapim/gateway:9.3.00
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8000:8000"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ./deployment/build/gateway/deployment-0.6.0.gw7:/opt/docker/rc.d/deployment.gw7
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      EXTRA_JAVA_ARGS: "-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
      "ENV.IDENTITY_PROVIDER.my-ldap": '{
                            "type": "BIND_ONLY_LDAP",
                         "environmentVariables": {
                           "key1":"value1",
                           "key2":"value2"
                         },
                         "identityProviderDetail": {
                           "serverUrls": [
                             "ldap://host:port",
                             "ldap://host:port2"
                           ],
                           "useSslClientAuthentication":false,
                           "bindPatternPrefix": "somePrefix",
                           "bindPatternSuffix": "someSuffix"
                         }
                         }'
      ENV.PASSWORD.my-password: asd
secrets:
  license:
    file: ./docker/license.xml